### ISSUE TITLE
Could NOT find PythonLibs (missing: PYTHON_LIBRARIES 

### ISSUE THREAD

**Issue by tseemann** [fwhelan/coinfinder#10]
I am guessing maybe my cmake is broken but thought I would ask:

```
% cmake .
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
```

If i comment out the directive in `Cmakelists.txt` when i compile it cant find `Python.h` but I do have it and pkg-config can find it:

```
% python3-config --includes --libs

-I/home/linuxbrew/.linuxbrew/include/python3.7m -I/home/linuxbrew/.linuxbrew/include/python3.7m
-lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm

```

**Comment by tseemann** [comment]
I made some progress with

```
cmake .
-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
-DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
```
but errors at link stage.

**Comment by fwhelan** [comment]
Hi tseemann,

Sorry for the delay. I've used the last week to get `coinfinder` up on Bioconda. We can work through the above together, but I imagine that you might prefer to install via conda with `conda install -c conda-forge -c bioconda -c defaults coinfinder`.

Let me know if this helps or if you'd like to work through the cmake option! Thanks for your patience with this!

**Comment by tseemann** [comment]
I was trying to packaged it into `Homebrew` that's where the errors come from. I am not skilled enough with Cmake to understand its interactions with determining Python paths unfortunately. This is not urgent.

**Comment by fwhelan** [comment]
I'm not very familiar with `Homebrew` but if you got me started with a partial formula, maybe I could play around locally with getting the cmake parts working?

**Comment by fwhelan** [comment]
I'm going to close this due to inactivity but please feel free to reopen if you'd like to work together to get something up on `Homebrew`!

**Comment by tseemann** [comment]
I don't think i have the time or skill to figure this one out.
If it would `pip3 install` that would help maybe

**Comment by astroza** [comment]
> I made some progress with
> 
> ```
> cmake .
> -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
> -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
> ```
> 
> but errors at link stage.

I had success in another project the the same issue (nextpnr) adding the dylib filename to PYTHON_LIBRARY as follows:
print(sysconfig.get_config_var('LIBDIR')+'/libpython3.7.dylib')

Maybe it works for you too

**Comment by lidanqing-vv** [comment]
> > I made some progress with
> > ```
> > cmake .
> > -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
> > -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
> > ```
> > 
> > 
> > but errors at link stage.
> 
> I had success in another project the the same issue (nextpnr) adding the dylib filename to PYTHON_LIBRARY as follows:
> print(sysconfig.get_config_var('LIBDIR')+'/libpython3.7.dylib')
> 
> Maybe it works for you too

Thank you very much, it works for me
