### ISSUE TITLE
Can you turn off bonferroni significance correction? 

### ISSUE THREAD

**Issue by cocathail** [fwhelan/coinfinder#11]
Hi (again),

Is there a way to turn off the significance correction step in the pipeline? I've a small set (60) E. coli genomes that are reasonably similar but I know from manually parsing the genomes I've 2 genes that only exist together in one isolate and not in the others. Coinfinder doesn't seem to pull this out. I am wondering is this because of the bonferroni correction step? It reduces the significance threshold from 0.05 down to 2.09e-09..... I'd doubt anything would pop out as significant in this case?

Just asking but maybe what I'm trying to make coinfinder do isn't what it's really meant for....

Colman

**Comment by fwhelan** [comment]
Hi Colman,

While it isn't suggested behaviour, there is an option to adjust the significance correction step by changing `-m` to `-n`. (I've just added the output of `coinfinder -h` to the main page to help clarify `coinfinder's` usage.)

If you're looking for a gene pair that's only in 1 isolate, I would suggest that you disable filtering before playing around with the stats. `Coinfinder` by default filters genes that are found in <5% of genomes. You can alter this with the `-F` flag (or turn it off completely with `-F 0`).

Let me know if that's helpful!
--Fi

**Comment by cocathail** [comment]
Yes this has turned out to be useful! Thank you. Sorry for the issue raise again!
