### ISSUE TITLE
Heatmap generation error

### ISSUE THREAD

**Issue by bjtully** [fwhelan/coinfinder#13]
Hi!

Not sure if this is my dataset or another issue. Installed coinfinder (Dec 17, 2019) using conda.
Ran this command: `coinfinder -i roary_output/gene_presence_absence.csv -I -p SM1A02.msa.newick -x 32 --associate -n`
The dataset I am running is of a Family level clade of 38 genomes. I did not receive significant matches when using the Bonferroni correction, but I wanted to see if there were any matches using the p = 0.05 cutoff.

It ran successful until this point:
```
Reading arguments...
> CORRECTION ······· = NONE
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = NO
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = roary_output/gene_presence_absence.csv
> ALPHA_NAME ······· = Alpha
> BETA_NAME ········ = Beta
Formating Roary output for input into coinfinder...
Reading alpha-beta edges...
- n.ALPHA = 66940
- n.BETA  = 38
- n.GAMMA = 0
- n.EDGES = 86589
Dropping saturated sets...
Nothing dropped due to node saturation, your data is good to go. :)
Dropping rare elements in collection...
**Warning**: Rare elements have been dropped!
- d.ALPHA = -55140
- n.ALPHA = 11800
- n.BETA  = 38
- n.GAMMA = 0
- n.EDGES = 86589
Dropping empty sets...
Nothing dropped, your data is good to go.
Iterating matrix...
No significance correction, the significance level is 0.05.
Running analyses...
Calculating lineage dependence...
Generate coincidence heatmap...
ERROR MESSAGE FROM R:
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 91612 did not have 3 elements
Calls: read.table -> scan
Execution halted
```
I'm guessing something about way R is reading the tables, but it is unclear to me what this may be.

Cheers
Ben

**Comment by fwhelan** [comment]
Hi Ben,
Sorry that you're running into this issue! I was wondering if you could be able to take a look at the `_edges.tsv` file that should be in your output folder and see what line 91,612 looks like? It should have 3 columns: a gene name, a second gene name, and a p-value. I'm wondering if there was an issue creating this file and that maybe that's what we're seeing here.
I know debugging isn't much fun, so if its easier for you, feel free to send me your gene and phylogeny inputs and I can sort out the bug on my end.
Cheers,
Fiona

**Comment by bjtully** [comment]
Line 91612 `apbE    group_55684     0.00504846`

Happy to send files your way.

**Comment by fwhelan** [comment]
Hi Ben,
Sorry for the delay over the holidays! I was able to reproduce the error you ran into with your data (thanks for sending it on!). It turns out it was due to you having a gene name with a single quote in it. I had code in Coinfinder to work with illegal characters, which worked in most cases; but R struggled with the single quote, thinking that it was a field delimiter. I've updated the R code and reran your data through just fine, so if you grab the newest version of Coinfinder from github, you should be good to go! If you'd rather use the conda install, let me know and just give me a day or so to get a new version pushed through the bioconda community.
Cheers,
Fiona

**Comment by fwhelan** [comment]
I'm going to close this due to inactivity, but please feel free to reopen if you're still having issues.
