### ISSUE TITLE
conda install not working on osx?

### ISSUE THREAD

**Issue by fwhelan** [fwhelan/coinfinder#14]
I've read rumblings that this is true and am in the process of attempting a fix to the bioconda recipe (any input appreciated). However, it would be helpful if anyone who has tried a conda install on osx could confirm or deny that this is an issue, and perhaps provide output of the command as well.

**Comment by fwhelan** [comment]
thanks to the *amazing* people at bioconda, coinfinder should now be installable on osx architectures. if you run into any issues, please reopen this issue and we'll take a look!

**Comment by gregwood-db** [comment]
@fwhelan Looks like this issue has come back around- I'm currently unable to install using Conda/Bioconda on OSX (10.14.6) and Conda 4.8.4. Creating a fresh env with `conda create -n coinfinder_env -c conda-forge -c bioconda -c defaults coinfinder` hangs indefinitely while solving the environment. Happy to test this out with some other setups if necessary.

**Comment by fwhelan** [comment]
ah darn, my apologies. I was really hoping this had finally been resolved. I will take a good look at this first thing tomorrow.

**Comment by fwhelan** [comment]
I've submitted a pull request but the conda build times out on the MacOS tests. If you know anything about bioconda and have any thoughts, that would be great! I'll have more time to put to this properly next week; in the meantime, the bioconda install is working on Ubuntu or native install on macOS is also an option. I'll post more updates here as things progress- apologies for the delay with this.

**Comment by fwhelan** [comment]
Coinfinder now passes the macos build tests on bioconda. The pull request should be merged and available to you within the next 24 hours or so.

**Comment by fwhelan** [comment]
Or whenever the pull request is approved! There is a bit of a backlog of requests to bioconda-recipes at the moment, but hopefully this will be resolved soon. Again, apologies!

**Comment by fwhelan** [comment]
v1.0.5 of coinfinder is now up on bioconda. Thanks so much for your patience; let me know if you run into any other issues!

**Comment by gregwood-db** [comment]
@fwhelan thanks so much and sorry for the late response here- I'll give this a try later today but I appreciate the update!!

**Comment by fwhelan** [comment]
Definitely re-open the issue if you run into any problems!!
