### ISSUE TITLE
explicitly point compiler to gcc with macOS

### ISSUE THREAD

**Issue by slhogle** [fwhelan/coinfinder#15]
```
$ cmake --build .
clang: error: unsupported argument 'libomp' to option 'fopenmp='
```

macOS uses `clang` as default compiler not `g++` so the system `gcc` points to `clang`:

```
$ which gcc
/usr/bin/gcc
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

you will need to point the compiler to gcc 

For example (if u installed w/ homebrew and have symlinks in /usr/local/bin)

`export CC=/usr/local/bin/gcc-6; CXX=/usr/local/bin/g++-6; MPICXX=/usr/local/bin/mpic++`

Might be useful information for others compiling on macOS. I was able to successfully compile on High Sierra 10.13.6

cheers
-shane

**Comment by fwhelan** [comment]
Thanks, Shane! I'll add this to the Installation notes now for others. Really appreciated!
