### ISSUE TITLE
Calculating lineage dependence - file reading error

### ISSUE THREAD

**Issue by kujawskm** [fwhelan/coinfinder#18]
Hi Fiona,
I have compiled coinfinder on a virtual linux machine run on MacOS Catalina (as had problems with MacOS installation that I haven't sorted out yet, but was very keen to try your software :-) ).
When I run it on your test data, below - or any other data for that matter - it stops at the lineage dependence step and it seems it can't open a *_nodes.csv file. The *_nodes.csv is indeed not created as an output, but another file called *_nodes_in.csv is. Can you comment on this please? Is this an intermediate file of some sort, or an error in file naming? Can you think of a solution?  

Thanks,
--Magdalena

```
m@m-VirtualBox:~/Tools/coinfinder$ ./coinfinder -i test/gene_presence_absence.csv [-I] -p test/tree.newick -o test/output --associate -x 4
Reading arguments...
> CORRECTION ······· = BONFERRONI
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = NO
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = test/gene_presence_absence.csv
> ALPHA_NAME ······· = Alpha
> BETA_NAME ········ = Beta
Formating Roary output for input into coinfinder...
Reading alpha-beta edges...
- n.ALPHA = 8583
- n.BETA  = 534
- n.GAMMA = 0
- n.EDGES = 1089700
Dropping saturated sets...
**Warning**: Saturated data has been dropped!
- d.ALPHA = -711
- n.ALPHA = 7872
- n.BETA  = 534
- n.GAMMA = 0
- n.EDGES = 1089700
Dropping rare elements in collection...
**Warning**: Rare elements have been dropped!
- d.ALPHA = -5059
- n.ALPHA = 2813
- n.BETA  = 534
- n.GAMMA = 0
- n.EDGES = 1089700
Dropping empty sets...
Nothing dropped, your data is good to go.
Iterating matrix...
Bonferroni significance correction, given 3957891 tests, the significance level has been reduced from 0.05 to 1.2633e-08.
Running analyses...
Calculating lineage dependence...
Error: unable to open test/output_nodes.tsv
Generate coincidence heatmap...
Generate network...
grep: test/output_components.tsv: No such file or directory
Error: Gexf could not find the alpha name Int.Tn in the components file.
All done!
```

```
m@m-VirtualBox:~/Tools/coinfinder$ ls test -lhtr
total 68M
-rw-r--r-- 1 m m  56M Mar 26 10:52 gene_presence_absence.csv
-rw-r--r-- 1 m m  34K Mar 26 10:56 tree.newick
-rw-r--r-- 1 m m 8.0M Mar 26 12:37 output_pairs.tsv
-rw-r--r-- 1 m m  19K Mar 26 12:37 output_nodes_in.csv
-rw-r--r-- 1 m m 3.3M Mar 26 12:37 output_edges.tsv
-rw-r--r-- 1 m m    0 Mar 26 12:37 output_network.gexf
```

**Comment by fwhelan** [comment]
Hi Magdalena,

Sorry to hear you're running into this issue. The `output_nodes.tsv` is actually generated by the R code in the `Calculating lineage dependence step`; it looks like something might be going wrong in this R code, so when it returns back to C++ and tries to open `output_nodes.tsv`, it fails.

Could you please add `-R` to the end of your coinfinder call? This is a debugging flag that outputs all messaging from R- this might give us a hint as to what's going on. (Additionally, you don't need the []s around -I; `./coinfinder -i test/gene_presence_absence.csv -I -p test/tree.newick -o test/output --associate -x 4 -R` should do the trick).

Let me know what that shows! Hopefully it's as simple as a missing R package :).

Cheers,
Fiona

**Comment by kujawskm** [comment]
Hi Fiona,

Many thanks for getting back to me! You were absolutely right, it was an issue caused by a missing R package that could not install as there were missing libraries on my virtual linux - I missed the error message during initial installation in R. Fixed it and everything works perfectly now :-) 
Thanks again, I am closing this issue.

Cheers,
Magdalena

**Comment by fwhelan** [comment]
Great news, Magdalena! Thanks for letting me know how it worked out :).
