### ISSUE TITLE
R error (lineage.R)

### ISSUE THREAD

**Issue by olga216** [fwhelan/coinfinder#2]
Hi, 

I would like to find the associations between gene pairs. Before I use a large dataset, I decided to run Coinfinder with a small sample (6 draft genomes with more than 95% nucleotide similarities between them), however, the final result shows that there are not any significant coinciding pairs (the p-values after the Bonferroni correction are too low (e-10)). 
I try to use --nocorrection, but it did not work.  Then, I got some significant pairs (p-value < 0.0002), when I increased the –-level (p-value) and reduced the number of genes in the pangenome matrix (see command line). 

./coinfinder -i gene_presence_absence_new.csv -p tree.newick -o test_1 --associate -I --level 100 --num_cores 8 -v &> verbose_1.txt

Unfortunately, after I got the pairs I got the following error message:

Calculating lineage dependence...
ERROR MESSAGE FROM R: 
Error in `.rowNamesDF<-`(x, value = value) : 
  missing values in 'row.names' are not allowed
Calls: rownames<- ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
Execution halted

Do you have any idea about why this error message pops up? Which version of R do you recommend to install? I am using macOS sierra (version 10.12.6).

Thank you.

**Comment by fwhelan** [comment]
Hi olga216,

I've fixed the bug that was preventing `--nocorrection` from working, so you should be able to use that now.

The error that you're getting during the lineage dependence calculation looks like it might be related to your `gene_presence_absence_new.csv`. It's possible that however you edited this file from the original might have altered the formatting in some way- for example, with altered line endings. Could you try the `--nocorrection` with your original `gene_presence_absence.csv` and let me know if you get the same error from R?

**Comment by olga216** [comment]
Thank you so much! --nocorrection is working. Also, the R error is gone, the format of my gene_presence_absence.csv file was altered, the quotation marks were missed “”.
