### ISSUE TITLE
error: Phylogeny contains zero length internal branches

### ISSUE THREAD

**Issue by fabiogvb** [fwhelan/coinfinder#20]
Hi @fwhelan ,
I am trying to use the coinfinder but I had the message error: Phylogeny contains zero length internal branches. I guess it is a common problem in phylogeny, but I do not have idea how to solve it. 
How could I treat a phylogeny containing zero length internal branches with di2multi in order to pass in clusterApply -> staticClusterApply -> checkForRemoteErrors?

I found this but I am not sure where and how to use it. Could you help me?

 http://blog.phytools.org/2013/12/new-di2multi-function-for.html
 collapse branches of zero length
tree<-di2multi.simmap(tree)

./coinfinder -i tab-delimited.tab -p 348.SpeciesTree_rooted_node_labels.txt -o output -x 7
Reading arguments...
> CORRECTION ······· = BONFERRONI
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = NO
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = tab-delimited.tab
> ALPHA_NAME ······· = Alpha
> BETA_NAME ········ = Beta
Formating input into gene_p_a for input into coinfinder...
Reading alpha-beta edges...
- n.ALPHA = 33046
- n.BETA  = 348
- n.GAMMA = 0
- n.EDGES = 1441120
Dropping saturated sets...
**Warning**: Saturated data has been dropped!
- d.ALPHA = -55
- n.ALPHA = 32991
- n.BETA  = 348
- n.GAMMA = 0
- n.EDGES = 1441120
Dropping rare elements in collection...
**Warning**: Rare elements have been dropped!
- d.ALPHA = -24469
- n.ALPHA = 8522
- n.BETA  = 348
- n.GAMMA = 0
- n.EDGES = 1441120
Dropping empty sets...
Nothing dropped, your data is good to go.
Iterating matrix...
Bonferroni significance correction, given 36316503 tests, the significance level has been reduced from 0.05 to 1.37678e-09.
Running analyses...
Calculating lineage dependence...
ERROR MESSAGE FROM R: 
Error in checkForRemoteErrors(val) : 
  7 nodes produced errors; first error: Phylogeny contains zero length internal branches. Use di2multi.
Calls: <Anonymous> ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted

errors; first error: Phylogeny contains zero length internal branches. Use di2multi.
Calls: <Anonymous> ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted

**Comment by fwhelan** [comment]
Hi fabiogvb,

You could do something like this (collapsing zero length branches) with your tree in R prior to input into coinfinder.

**Comment by fabiogvb** [comment]
Hi @fwhelan ,
Thank you so much for your speedy reply. I collapsed the tree using d2multi and itol prior to input into coinfinder but I still have the same error. The tree has not zero length branches, but some values like 0.00034964. How many digits after decimal are used in coinfinder?  Is there some limit on phylogenetic groups?
I used  ctree <- di2multi(tree, tol = 0.1)

**Comment by fwhelan** [comment]
Hi fabiogvb,

The code that checks for zero length branches is in `coinfind-code/check_zeroes.R` if you'd like to take a look.  Essentially, it checks for whether there is a 0 in the edge.length vector; if this returns TRUE, then coinfinder exits with an error message, "Error: Input phylogeny contains branch lengths which equal zero."

I hope that helps!

**Comment by fabiogvb** [comment]
Hi @fwhelan ,
Could you send me a test dataset (tree and matrix)? 
The code coinfind-code/check_zeroes.R returns FALSE for my dataset. The error message is different, like line 68 https://github.com/cran/caper/blob/master/R/phylo.d.R
I am using R version 3.6.3
Please, could you print the output for below commands?
sessionInfo()
packageVersion("caper")

Thank you so much!

**Comment by fwhelan** [comment]
Closed due to inactivity; feel free to reopen as necessary.
