### ISSUE TITLE
Running coinfinder with self-created dataset!

### ISSUE THREAD

**Issue by maesaar** [fwhelan/coinfinder#23]
Hello,

I have few questions regarding running coinfinder with self-created dataset:

1) For example I will create tab-delimited list of genes present in each strain does the strain names need to be the same as in phylogeny?

2) What does phylogeny of betas mean?

3) For phylogeny is it better to use core phylogeny with recombination or recombination corrected (e.g. ClonalFrameML)?

4) Is there minimum genes count for the software to give meaningful results - what is smallest overall gene count needed? Is six genes too small?

Thank you

**Comment by fwhelan** [comment]
Hello,
Thanks for your interested in coinfinder. I've tried to answer your questions as best as I can:
1. Yes, the strain names in your tab-delimited input will have to match those on the phylogeny.
2. This is a phylogeny of the genomes, of the strains that you provide (alphas and betas was our working terminology as coinfinder was being developed; I've tried to replace all mentions with genes and genomes but apparently I've missed some! I'll update the readme now to be more clear.)
3. This is up to you and will be strain dependent- whatever recapitulates the relationships between your strains the best.
4. There isn't necessarily a minimum gene count, but we set our default to cull any gene that's present in <5% of the input strains. Table 3 and the associated discussion in our [publication](https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000338) describing coinfinder may be helpful.

**Comment by maesaar** [comment]
Thank you! One more thing I have problem with conda install - it freezes in "solving environment" stage. I am using MacOS

**Comment by fwhelan** [comment]
There appears to be a recent update to bioconda that is preventing a few packages from working properly and I think coinfinder might have been affected. I've flagged for help on the bioconda github but it might take a few days to be resolved.

**Comment by maesaar** [comment]
Thank you!

**Comment by fwhelan** [comment]
Hi mmaesaar, the issues with bioconda look to have been sorted out; if you're still having issues on MacOS you might retry it now.

**Comment by fwhelan** [comment]
I'm going to close this issue due to inactivity but let me know if you have any further questions.

**Comment by maesaar** [comment]
Issues on MacOS is solved!

**Comment by maesaar** [comment]
Hello @fwhelan I have problem using coinfinder. I get following error:
```
dyld: Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/Python
  Referenced from: /Users/username/miniconda3/bin/coinfinder
  Reason: image not found
Abort trap: 6
```

**Comment by maesaar** [comment]
Hi again! I switched to Linux and got `coinfinder` working, but now when using self-created dataset in `"gene<tab>genome"` format I get following error:
`ERROR MESSAGE FROM Python: 
Traceback (most recent call last):
  File "./coinfind-code/create_roary.py", line 68, in <module>
    gen = (line.split("\t")[1]).strip()
IndexError: list index out of range
`

**Comment by maesaar** [comment]
Somehow it has now been resolved.
