### ISSUE TITLE
Roary paralog splitting & MacOS installation!

### ISSUE THREAD

**Issue by nbawe** [fwhelan/coinfinder#26]
When using `roary` output as an input to `coinfinder` how to handle `-s` (paralog splitting) parameter. Should the `-s` parameter in roary be used or not?

Second, have you had time to fix coinfinder installation on MacOS?

**Comment by fwhelan** [comment]
That's up to you and your research question. Coinfinder will treat each gene cluster (i.e. line in the Roary output) as a separate entity so its up to you whether you would like to split paralogs in your run of Roary or not; Coinfinder can handle both ways.

I'm currently working on the MacOS issue.

**Comment by nbawe** [comment]
Thanks @fwhelan  please tell us when MacOS issue is resolved.

**Comment by nbawe** [comment]
Thank you @fwhelan conda install works now!
