### ISSUE TITLE
How to generate association network?

### ISSUE THREAD

**Issue by tauqeer9** [fwhelan/coinfinder#27]
Hello
I am able to make heat map from the gene presence absence and core genome tree. Can anyone help me how to generate association network as shown in Figure A of the example.

Thanks

Tauqeer

**Comment by fwhelan** [comment]
Hi Tauqeer,
The network in Figure A was made by opening the .gexf output file in the software Gephi, and choosing the Fruchterman Reingold layout option. If you have a lot of data, the layout might take a few hours to resolve.

Let me know if that helps!

**Comment by charlottecc** [comment]
Hi Fiona, 

I have run coinfinder and am currently running the Fruchterman Reingold layout option in Gephi. I was just wondering if you have more information about why you use this algorithm? 

Thanks in advance! 

Charlotte

**Comment by fwhelan** [comment]
Hi Charlotte,

Thanks for using coinfinder! Not really unfortunately; there are a few different options in Gephi (as I'm sure you've seen) and the algorithm seemed to display that data in the most visually appealing and easiest to understand way. However, we've definitely used other options for networks of different shapes and sizes.

I hope that helps!

-Fiona

**Comment by charlottecc** [comment]
Thanks for getting back to me with that info Fiona!
