### ISSUE TITLE
How to remove columns from roary-style input file

### ISSUE THREAD

**Issue by jamiethompson77** [fwhelan/coinfinder#28]
Two of my sequences are exactly identical to others, as identified by RAxML, and I removed these two prior to making my tree.  In the gene presence/absence file (roary format), I need to remove these columns before using coinfinder but don't know exactly how this will affect the analysis.  Are the first 14 columns of the roary file (from "Gene", to "Avg group size nuc") read by coinfinder?

**Comment by fwhelan** [comment]
The first 14 columns are read and ignored by coinfinder. The best thing to do, in this case, would be to remove just the column(s) that correspond to the genome(s) you would like to remove. Hope that helps!

**Comment by jamiethompson77** [comment]
OK thanks for the advice!  Also, I'm not sure if you could help me with installation.  I updated my python from 2.7 to 3.8 according to an error message given while trying to install Coinfinder.  Now it has updated the problem still remains.

**Comment by fwhelan** [comment]
Could you clarify what the error message or problem is? You could try to install via `bioconda`; that's arguably the easiest option.

**Comment by fwhelan** [comment]
I'm going to close this issue due to inactivity, but feel free to reopen if you're still having problems.
