### ISSUE TITLE
Error in using coinfinder

### ISSUE THREAD

**Issue by vigneshlab** [fwhelan/coinfinder#32]
Hi, I installed coinfinder using conda. 

Typing coinfinder on the terminal gives the following: 
> CoinFinder 1.1 
> RELEASE BUILD @ Oct  7 2020 12:06:08.
> Please see readme.md for details.

I downloaded the dataset from [https://github.com/fwhelan/coinfinder-manuscript](url) and when I try use the gene-presence-absence.csv file, it throws up the following error: 

$coinfinder -I gene_presence_absence.csv 
Reading arguments...
> CORRECTION ······· = FRACTION (special)
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = YES
> VERBOSE ·········· = YES
> OUTPUT_ALL ······· = NO
terminate called after throwing an instance of 'std::logic_error'
  what():  Cutoff mode specified when method != CONNECTIVITY.
Aborted (core dumped) 

Could you please help resolve the issue?

**Comment by noahaus** [comment]
Hi, I recently ran coinfinder and noticed that there may be an error in how you called your command. try following this syntax and it may work?

```
 coinfinder -i mbovis_prab.csv -I -p core_gene.collapsed.tre -o mbov_pan.coin
```

**Comment by vigneshlab** [comment]
Thank you! It works now!

**Comment by vigneshlab** [comment]
I tried to use the tab-limited input format suggested in the readme file. When I use the example given in the readme file, it works fine. However, when I add a few more lines (gene 4) such as below, I get error (mentioned below): 

> gene_1  genome_1
> gene_1  genome_2
> gene_1  genome_3
> gene_2  genome_2
> gene_2  genome_3
> gene_3  genome_1
> gene_3  genome_2
> gene_4  genome_1
> gene_4  genome_2
> gene_4  genome_3

$coinfinder -i gene.txt -a

> Reading arguments...
> > CORRECTION ······· = BONFERRONI
> > METHOD ··········· = COINCIDENCE
> > ALT_HYPOTHESIS ··· = GREATER
> > MAX_MODE ········· = ACCOMPANY
> > SET_MODE ········· = FULL
> > PERMIT_FILTER ···· = NO
> > VERBOSE ·········· = NO
> > OUTPUT_ALL ······· = NO
> > FRACTION CUTOFF ·· = N/A
> > SIGNIFICANCE_LEVEL = 0.05
> > COMBINED_FILE ···· = gene.txt
> > GENE_NAME ······· = Genes
> > GENOME_NAME ········ = Genomes
> 
> You have not provided a phylogeny. This is okay, coinfinder works just fine without a phylogeny. The steps involving the detection of lineage dependent elements will be skipped.
> 
> **Please be aware that coinfinder will generate a mock phylogeny for the purposes of data presentation in the output heatmaps.**
> 
> Press any key to accept and continue or Ctrl+C to quit.
> 
> Formating input into gene_p_a for input into coinfinder...
> ERROR MESSAGE FROM Python: 
> Traceback (most recent call last):
>   File "/opt/miniconda3/bin//coinfind-code/create_roary.py", line 68, in <module>
>     gen = (line.split("\t")[1]).strip()
> IndexError: list index out of range

Please help. Thanks.

**Comment by fwhelan** [comment]
Hi vigneshlab,

It looks like your modifications to the gene.txt file might not keep to the gene</t>genome</n> format? I usually check this in `vim` using `:set list` though there are many ways!

Let me know if that helps!

**Comment by vigneshlab** [comment]
> Hi vigneshlab,
> 
> It looks like your modifications to the gene.txt file might not keep to the genegenome format? I usually check this in `vim` using `:set list` though there are many ways!
> 
> Let me know if that helps!

Thanks fwhelan. It helped. There were issues with the format. vim set list was useful. :+1:
