### ISSUE TITLE
Scoary + Coinfinder: Network Metrics Interpretation 

### ISSUE THREAD

**Issue by noahaus** [fwhelan/coinfinder#33]
Hello,

I have done some quick analysis for a project I am working on, and it involves trying to determine how enriched genes affect other genes in the pangenome. 

To describe quickly, I used Scoary to infer which genes are enriched in different countries, and then I used coinfinder output to find how these enriched genes connect to other genes. that coincide with the enriched genes. I was able to create the following figure based off this analysis:

![image](https://user-images.githubusercontent.com/40697188/97755062-e73c3580-1ace-11eb-87a5-a9ff95b959dc.png)
 Here, the node colors represent an enriched gene in a certain country, while gray nodes indicate that these genes are not necessarily enriched, but they are detected to coincide together using Coinfinder.

I next collected several network statistics to see how they differed between countries, and was able to see some heterogeneity in the statistics:

 
![image](https://user-images.githubusercontent.com/40697188/97755514-b90b2580-1acf-11eb-9a09-4a76846e7bd5.png)

Now here is my question: If I get network statistics, such as degree or closeness, how can I extend their interpretation for the output of Coinfinder? I imagine that genes that are highly connected might be very important overall, but I'm stuck as to what this might mean biologically. Is there a paper the developers could potentially point me to for understanding this relationship?

Any help would be greatly appreciated.

**Comment by fwhelan** [comment]
Thanks for your question, noahaus! It looks like you're doing some really interesting work! I know there is quite substantial literature on the use of network statistics in ecology/biology in general, but unfortunately I can't think of a specific study that would be of direct interest to your work here. Myself and others have just posted a preprint to bioRxiv that uses coinfinder and does look at highly connected "hub" genes, but even that doesn't really get to what you're interested in here.

Sorry that I can't be of more help!

**Comment by noahaus** [comment]
This has been plenty help, thank you. I will close the issue, but will add papers as I find out more in a targeted review. Thank you again!
