### ISSUE TITLE
'std::logic_error' while running coinfinder?

### ISSUE THREAD

**Issue by dineshkumarsrk** [fwhelan/coinfinder#35]
I tried to run your manuscript datasets for confirmation with the following command
`(base) ga@ga-214:~/Documents/tools/coinfinder$ coinfinder -I gene_presence_absence.csv -p gene_presence_absence.csv`
but end with the following error,
```
Reading arguments...
terminate called after throwing an instance of 'std::logic_error'
what():  More than one value for the 'permit_filter' setting has been specified.
Aborted (core dumped)
```
```
For your information, My computer configaration as follows,
OS: Ubuntu16.04 LTS 64 bit version
RAM: 6 GB RAM
CPU(s): 8 (core i7 processor)
Harddisk: 500GB (400GB is free as of now)
```
When I tried with my own data also I get this same error. My pangenome also carried out by Rorary pipeline. I have tried another computer with similar configuration with Ubuntu 18.04 LTS also gives the same error.
Please help me to fix this issue.

**Comment by fwhelan** [comment]
Hi dineshkumarsrk,

Please see the example Usage on the landing page of this github; specifically the `-p` flag expects a phylogeny file to follow it, not a gene presence/absence matrix. Also, if your data is in Roary format, coinfinder expects `-i gene_presence_absence.csv -I ...`.

Hope that helps.

**Comment by dineshkumarsrk** [comment]
@fwhelan , by mistake I had shown you the wrong command line earlier. As you mentioned I had entered the following command 
```
(base) dinesh@dinesh7k:~/Documents/tools/coinfinder-master$ coinfinder -I gene_presence_absence.csv -p core-gps_fasttree.newick -o dinesh 
Reading arguments...
terminate called after throwing an instance of 'std::logic_error'
  what():  More than one value for the 'permit_filter' setting has been specified.

Aborted (core dumped)
```
despite I am ending up the same error which I got earlier. Even I tried with both -i and -I flag and getting error only,
```
(base) dinesh@dinesh7k:~/Documents/tools/coinfinder-master$ coinfinder -i gene_presence_absence.csv -p core-gps_fasttree.newick -o dinesh 
Reading arguments...
> CORRECTION ······· = BONFERRONI
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = NO
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = gene_presence_absence.csv
> GENE_NAME ······· = Genes
> GENOME_NAME ········ = Genomes
Formating input into gene_p_a for input into coinfinder...
ERROR MESSAGE FROM Python: 
Error: input file gene_presence_absence.csv does not appear to be in the format geneFamily<tab>genome
Did you mean to include the -I flag to indicate a Roary formatted input file?
Exiting...
```

**Comment by fwhelan** [comment]
Please try `coinfinder -i gene_presence_absence.csv -I -p core-gps_fasttree.newick -o dinesh`

**Comment by fwhelan** [comment]
Closed due to inactivity; please feel to re-open if you're still having issues with this dataset.
