### ISSUE TITLE
Bioconda install hangs on Solving Environment:...

### ISSUE THREAD

**Issue by fwhelan** [fwhelan/coinfinder#36]
This is a known problem with how the `conda-forge` and `bioconda` channels communicate with each other.

Things to try:
1. Reordering the channels:
`conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge`
see here for more details: https://www.biostars.org/p/470291/

2. Removing and readding the `conda-forge` channel then updating conda:
`conda config --remove channels conda-forge
conda config --add channels conda-forge
conda update conda`
see here for more details: https://stackoverflow.com/questions/63734508/stuck-at-solving-environment-on-anaconda

Please comment below if you find that these help (or don't) or other work arounds that you've found.

**Comment by StephanieRodrigues** [comment]
Dear Fiona.
How are you?
I'm in trouble. I think this problem is happening with me. 
I tried the two alternatives that you mentioned. But I'm still having problems in part of Solving env. 

(Coinfinder) users-MacBook-Air:~ Stephanie$ conda install -c conda-forge -c bioconda -c defaults coinfinder
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 

I don't know what I can do. 

My bests,
Stephanie

**Comment by fwhelan** [comment]
Hi Stephanie,
I'm sorry to hear that you're running into this issue! Below are steps that have worked for another user who was having issues with Bioconda hanging and might be worth trying:

1. Create a new conda environment with python 3.6.9
2. Install Bioconductor-ggtree version 2.0.0 to that conda environment
3. Install Coinfinder to that conda environment.

Let me know if that helps!

**Comment by StephanieRodrigues** [comment]
Hi Fiona,
Not worked. Sorry.
In any case I was reading some issues on GitHub and I saw a question about run Coinfinder to small set of strains. My intention wa to run on a small group of genomes (less than 100 genomes). It al that I have! Do you think it's worth it? Or would the results not be reliable?


________________________________
De: Fiona J Whelan ***@***.***>
Enviado: terça-feira, 13 de abril de 2021 13:32
Para: fwhelan/coinfinder ***@***.***>
Cc: Stephanie Rodrigues ***@***.***>; Comment ***@***.***>
Assunto: Re: [fwhelan/coinfinder] Bioconda install hangs on Solving Environment:... (#36)


Hi Stephanie,
I'm sorry to hear that you're running into this issue! Below are steps that have worked for another user who was having issues with Bioconda hanging and might be worth trying:

  1.  Create a new conda environment with python 3.6.9
  2.  Install Bioconductor-ggtree version 2.0.0 to that conda environment
  3.  Install Coinfinder to that conda environment.

Let me know if that helps!

**Comment by fwhelan** [comment]
Hi Stephanie,

Could you give me a bit more detail as to how this failed? at exactly which step? For example, I just installed `coinfinder` on macOS Big Sur with the following:
```
conda update --all
conda create -n coinfinder-env python=3.6.9
conda activate coinfinder-env
conda install -c bioconda bioconductor-ggtree=2.0.0
conda install -c defaults -c bioconda -c conda-forge coinfinder
```
It took a bit of time to solve the environment (maybe ~10mins) but this is a known issue with the `conda-forge` and `bioconda` channels which is being worked on.

Re the size of your dataset, I would suggest reading the manuscript that describes coinfinder as it discusses this issue in detail and has a Table with some example calculations.

**Comment by StephanieRodrigues** [comment]
Hi Fiona!
I GOT IT!!!

I think patience was the key!
It took ~12/15 minutes.

As always appears at the beginning the message about failure to solve the environment. Last time I had this message and 5 minutes trying to solve the environment again and install, I thought I had failed again. THANK YOU SO MUCH FOR YOUR ATTENTION!!

And I'll read the paper!

Bests,

________________________________
De: Fiona J Whelan ***@***.***>
Enviado: terça-feira, 20 de abril de 2021 05:55
Para: fwhelan/coinfinder ***@***.***>
Cc: Stephanie Rodrigues ***@***.***>; Comment ***@***.***>
Assunto: Re: [fwhelan/coinfinder] Bioconda install hangs on Solving Environment:... (#36)


Hi Stephanie,

Could you give me a bit more detail as to how this failed? at exactly which step? For example, I just installed coinfinder on macOS Big Sur with the following:

conda update --all
conda create -n coinfinder-env python=3.6.9
conda activate coinfinder-env
conda install -c bioconda bioconductor-ggtree=2.0.0
conda install -c defaults -c bioconda -c conda-forge coinfinder


It took a bit of time to solve the environment (maybe ~10mins) but this is a known issue with the conda-forge and bioconda channels which is being worked on.

Re the size of your dataset, I would suggest reading the manuscript that describes coinfinder as it discusses this issue in detail and has a Table with some example calculations.

**Comment by gavinmdouglas** [comment]
If anyone else runs into problems with long solving times (which is a common problem for conda environments), using [mamba](https://github.com/mamba-org/mamba), which is a c++ implementation of conda usually will help.

You just need to swap in `mamba` (after installing it), for the conda install command:
```
mamba install -c defaults -c bioconda -c conda-forge coinfinder
```

**Comment by djvtrono** [comment]
using mamba solved my issue with long solving env times

**Comment by drelo** [comment]
Hi Fiona @fwhelan  I caught an error with pythools (it required maps and another packed) so I tried to install everything beforehand since entering _R_ and trying to manually reinstall didn't work maybe due to the fact I already have R in the system. 

Here are the lines that worked for me in case someone need them:

```
mamba create -c conda-forge  -n COIN  python=3.9 r-base=4.2.2  r-caper r-phytools r-getopt r-igraph r-dplyr r-cowplot r-data.table r-ggraph r-flock r-future r-globals
mamba activate COIN
mamba install -c bioconda bioconductor-ggtree=2.0.0
mamba install -c defaults -c bioconda -c conda-forge coinfinder
```

Cheers
