### ISSUE TITLE
heatmap question

### ISSUE THREAD

**Issue by spencer411** [fwhelan/coinfinder#37]
Just a question. When I run this program I get coin_heatmap0.pdf and coin_heatmap1.pdf. What is the difference here? Is the heatmap just split into two images because it is too large to show in one PDF, or is there something else I am missing? 

Just want to make sure I am interpreting my results correctly.

**Comment by fwhelan** [comment]
Hi spencer411. That's exactly it; the heatmaps are split into multiple files solely for the purposes of being able to read the gene cluster labels.
