### ISSUE TITLE
Potential Cmake issue

### ISSUE THREAD

**Issue by lizzietsai** [fwhelan/coinfinder#38]
I'm trying to run Cmake in order to build a Plasma client and after I put in the correct things in the "where's the source code" and the "where to put the binaries" boxes, and hitting "configure", I get the following error:

Call Stack (most recent call first):
  CMakeLists.txt:12 (include)

I'm not a developer so I don't know what this means. Any help would be greatly appreciated,

**Comment by lizzietsai** [comment]
Please disregard the message above. I was following incorrect instructions.


I am now following the instructions at this address:   https://github.com/H-uru/Plasma#compiling-instructions
I have installed Microsoft Visual Studio 2019 and have plugged in my repository; however, I get the following error: 

![error](https://user-images.githubusercontent.com/80180707/110676200-8f9e8c80-8188-11eb-9e5c-082ef117409d.png)

Also, when I go into Cmakesettings.Json and select x86-Release, it gives me a list of variables with check boxes next to them. 

![error 2](https://user-images.githubusercontent.com/80180707/110676377-bbba0d80-8188-11eb-871d-a5466f9c2b62.png)
What do these two things mean? Can anyone give me some assistance?

**Comment by fwhelan** [comment]
Hi lizzietsai,

Sorry, I don't have any experience with Windows and am not sure that coinfinder is able to be installed on a Windows-based machine. If that's all that is available to you, I would suggest looking into using a virtual unix-based environment or the ubuntu command line that I think now comes standard with Windows.
