### ISSUE TITLE
std::logic_error: More than one value for the 'permit_filter' setting has been specified

### ISSUE THREAD

**Issue by RCAFink** [fwhelan/coinfinder#39]
Hello Fiona, I was trying to run Coinfinder using a roary generated presence_absence csv using the command line as specified under usage, with no modification (except for the files I wanted to use for input, phylogeny, and prefix).
It gave me an error almost right away:
`libc++abi.dylib: terminating with uncaught exception of type std::logic_error: More than one value for the 'permit_filter' setting has been specified.`
Do you know what could be wrong?
Thank you!

NOTE: Issue resolved following the instructions at: https://github.com/fwhelan/coinfinder/issues/35#issuecomment-771635946?

**Comment by fwhelan** [comment]
Hi RCAFink,
Thanks for letting me know that you were able to solve your issue with #35. I'll work on making the error message a bit more helpful for this in the future. In the meantime, let me know if you run into any further issues with coinfinder! :)

**Comment by herber4** [comment]
<img width="889" alt="Screen Shot 2021-05-07 at 2 05 57 PM" src="https://user-images.githubusercontent.com/55756028/117490837-5a6eaa80-af3d-11eb-89de-558d4b7af295.png">

Hello, 

I am receiving this same error message. any ideas on how to get through it?

**Comment by RCAFink** [comment]
Yes, it’s actually simple: before the presence absence .CVS file you need to put -i after the file, you must put -I (for the roary format).
E.g., coinfinder -i <name file> -I -p <treefile> -o <output>
I hope this helps!
Ryan

Ryan C. Fink, Ph.D.
Sent from my iPhone

On May 7, 2021, at 15:06, herber4 ***@***.***> wrote:

﻿

[Screen Shot 2021-05-07 at 2 05 57 PM]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F55756028%2F117490837-5a6eaa80-af3d-11eb-89de-558d4b7af295.png&data=04%7C01%7CRCFink%40stcloudstate.edu%7C69ec6482897047da595b08d91182e06b%7C5011c7c60ab446ab9ef4fae74a921a7f%7C0%7C0%7C637560076105825340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hyk%2FRLKjwC19zWrdDBBJunxQ39HnkwI6fLMaIxwKs2A%3D&reserved=0>

Hello,

I am receiving this same error message. any ideas on how to get through it?
