### ISSUE TITLE
Error in checkForRemoteErrors(val)

### ISSUE THREAD

**Issue by rbcan** [fwhelan/coinfinder#4]
Dear fwhelan,

sorry for filing an issue again, but I seem to be unable to figure it out by myself.
I ran coinfinder with the following command

`./coinfinder -i ./input/genelist_coinfinder_in_shortnames.txt -p ./input/sup05_newick_shortnames.txt -o s05 --associate`

but I get this error below. I tried to run it without the tree and it successfully creates the heatmap. So it seems to be the step where it connects the data to the phylogeny. Any idea what it could be? I attached the files that I was using.
[genelist_coinfinder_in_shortnames.txt](https://github.com/fwhelan/coinfinder/files/3788685/genelist_coinfinder_in_shortnames.txt)
[sup05_newick_shortnames.txt](https://github.com/fwhelan/coinfinder/files/3788688/sup05_newick_shortnames.txt)

```
Reading arguments...
> CORRECTION ······· = BONFERRONI
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = NO
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = ./input/genelist_coinfinder_in_shortnames.txt
> ALPHA_NAME ······· = Alpha
> BETA_NAME ········ = Beta
Formating input into gene_p_a for input into coinfinder...
Reading alpha-beta edges...
- n.ALPHA = 19828
- n.BETA  = 134
- n.GAMMA = 0
- n.EDGES = 249453
Dropping saturated sets...
**Warning**: Saturated data has been dropped!
- d.ALPHA = -130
- n.ALPHA = 19698
- n.BETA  = 134
- n.GAMMA = 0
- n.EDGES = 249453
Dropping rare elements in collection...
**Warning**: Rare elements have been dropped!
- d.ALPHA = -15313
- n.ALPHA = 4385
- n.BETA  = 134
- n.GAMMA = 0
- n.EDGES = 249453
Dropping empty sets...
Nothing dropped, your data is good to go.
Iterating matrix...
Bonferroni significance correction, given 9616305 tests, the significance level has been reduced from 0.05 to 5.1995e-09.
Running analyses...
Calculating lineage dependence...
ERROR MESSAGE FROM R: 
Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: 'gene_10' only contains a single state.
Calls: <Anonymous> ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted
```

**Comment by fwhelan** [comment]
Hi rbcan,

Thank you so much for providing your dataset- it made debugging this issue so much easier! I've just pushed a fix that I think will clear up this issue, but I'm just running your data through now to be sure.

**Comment by rbcan** [comment]
Thank you so much! It works now :)
