### ISSUE TITLE
Erro in future package

### ISSUE THREAD

**Issue by StephanieRodrigues** [fwhelan/coinfinder#41]
Hey Fiona. 
I'm trying to run COINFINDER but i think I have problems in one of the R packages. I installed coinfinder (Last April) using conda but I had that issues for Mac users (solving environment forever ...). I don't know if this could be influenced. 
Here is the message: 

(coinfinder-env) users-MacBook-Air:COINFINDER Stephanie$ coinfinder -i gene_presence_absence_allFaecium.csv -I -p RAxML_allFaecium -o all_coinfinder -a
Reading arguments...
> CORRECTION ······· = BONFERRONI
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = NO
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = gene_presence_absence_allFaecium.csv
> GENE_NAME ······· = Genes
> GENOME_NAME ········ = Genomes
Formating Roary output for input into coinfinder...
Reading gene-genome edges...
- n.GENES = 14038
- n.GENOMES  = 144
- n.EDGES = 384639
Dropping saturated sets...
**Warning**: Saturated data has been dropped!
- d.GENES = -162
- n.GENES = 13876
- n.GENOMES  = 144
- n.EDGES = 384639
Dropping rare elements in collection...
**Warning**: Rare elements have been dropped!
- d.GENES = -8952
- n.GENES = 4924
- n.GENOMES  = 144
- n.EDGES = 384639
Dropping empty sets...
Nothing dropped, your data is good to go.
Iterating matrix...
Bonferroni significance correction, given 12125350 tests, the significance level has been reduced from 0.05 to 4.12359e-09.
Running analyses...
Calculating lineage dependence...
ERROR MESSAGE FROM R: 
Error: package or namespace load failed for ‘future’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘globals’ 0.12.4 is being loaded, but >= 0.12.5 is required
In addition: Warning message:
package ‘future’ was built under R version 3.6.3 
Execution halted

Bests,
Stephanie

**Comment by fwhelan** [comment]
Hi Stephanie,
In R (separate from running coinfinder) what is the output of `packageVersion("globals")`? If this is 0.12.4, it looks like a newer version is required. You can update the version by `install.package("globals")`.
Let me know if that helps!

**Comment by StephanieRodrigues** [comment]
Hi Fiona,
I opened my R studio and tried this. I didn't have the globals installed, so I installed the last version (0.14.0).
Then I run coinfinder again but at the end the same message. 
I checked and my R studio is the version 3.6.3. 
Maybe I don't understand, but how does coinfinder communicate with my R studio? Or did I do something wrong?
Sorry for the questions, I'm new in this world. 
Bests,

**Comment by fwhelan** [comment]
The R installation that RStudio uses is likely different from the R installation in your conda confinder-env environment. Could you try again but via typing `R` in the terminal where you're running coinfinder from to get an R command prompt?

**Comment by StephanieRodrigues** [comment]
Ok! Now I have the package.
I will try to run coinfinder again!
Thanks Fiona!

________________________________
De: Fiona J Whelan ***@***.***>
Enviado: terça-feira, 15 de junho de 2021 06:43
Para: fwhelan/coinfinder ***@***.***>
Cc: Stephanie Rodrigues ***@***.***>; Author ***@***.***>
Assunto: Re: [fwhelan/coinfinder] Erro in future package (#41)


The R installation that RStudio uses is likely different from the R installation in your conda confinder-env environment. Could you try again but via typing R in the terminal where you're running coinfinder from to get an R command prompt?

**Comment by StephanieRodrigues** [comment]
Got it Fiona!
