### ISSUE TITLE
Question about independent associate and dissociate binomial tests

### ISSUE THREAD

**Issue by gavinmdouglas** [fwhelan/coinfinder#44]
Hi Fiona,

Thanks for making this tool, it looks very useful!

I fear I am exposing my ignorance here, but why is it necessary to perform separate tests for association and dissociation? I would have thought that a two-tailed binomial test (with expected frequency = Pi ∗ Pj ∗ N) would capture both of these possibilities.

Thanks!

Gavin

**Comment by fwhelan** [comment]
Hi Gavin,

Apologies for not getting back to your question sooner- scrambling to catch up after taking some holidays!

I think the answer to your question really just reflects the evolution of coinfinder and what Martin and I had initially envisioned vs. where we ended up. We spent a long time trying to decide what the definition of "dissociation" should be in the hopes of best reflecting the underlying biology that we were interested in. We also could (and should) really refactor the code to make it a bit more user (and developer) friendly! I think you're completely right in that we made things harder on ourselves because the code was already in place to deal with the two scenarios separately.

Let me know if that hasn't fully answered your question- very happy to chat further (and very happy to adjust the code if we're found to be wrong!).

**Comment by gavinmdouglas** [comment]
Hey Fiona,

Thanks for the reply and that does answer my question! I was thinking that perhaps there would be increased statistical power if there was only a single test per gene. That's assuming that that the dissociation test on the lower tail of the test I described was equivalent to the current implementation - which might not be the case. I would be happy to dig into that to see how the results might change if you were interested. 


All the best,

Gavin

**Comment by fwhelan** [comment]
Sure! I'm always happy to hear about ways that we could improve coinfinder so I'd definitely be interested in anything you found! Thanks, Gavin!

**Comment by gavinmdouglas** [comment]
Ok sure, I'll let you know how the results change after running it on a test dataset with both approaches!

**Comment by gavinmdouglas** [comment]
Hey again,

After looking at the tool more closely it looks like the options for the tests to be greater/less/two-tailed or associate/dissociate basically encompasses the possibilities I was thinking of.

Anyway I ran all 6 combinations of options on dataset I've been working with just to get an idea of how the results change.

You can see the summary of the significant coincidence calls below. Basically it looks like the tests do result in very different outputs (i.e., that just doing a two-tailed test is very different from doing two separate one-tailed associate and dissociate tests). Similarly, the dissociate + greater and associate + less options result in very different outputs (many more pairs are called by dissociate+greater although all associate+less calls are included in that set).

Anyway, I just thought I would share in case this is useful for others trying to wrap their head around the tests!

![associate_test_venn](https://user-images.githubusercontent.com/12489683/137919949-34fa2019-9834-42c2-b24b-b3a783231bb6.png)

![dissociate_test_venn](https://user-images.githubusercontent.com/12489683/137919972-1d1fc997-c4b0-46aa-859b-5cb3bc871126.png)

**Comment by fwhelan** [comment]
Hmm.. I'm not sure that's the behaviour that I expected...

**Comment by fwhelan** [comment]
Actually, maybe I don't quite follow; what was the full call you used for, for e.g., the positive coincidence test, associate_two_tailed?

**Comment by gavinmdouglas** [comment]
That command looked like this:

```
./coinfinder -I \
                   -i gene_presence_absence_withquotes_for_coinfinder.csv \
                   -p core_gene_alignment.aln.nozero_for_coinfinder.treefile \
                   -o coinfinder_testing/associate_two_tailed \
                   --associate \
                   --twotailed
```

**Comment by fwhelan** [comment]
and the negative coincidence test, associate_two_tailed? I guess I'm not sure what differentiates the two Venn diagrams?

**Comment by gavinmdouglas** [comment]
Ah sorry for the confusion! The "associate_two_tailed" category corresponds to the same set of hits in both heatmaps (as does the"dissociate_two_tailed" category). I was thinking of the two tailed tests as being tests for both positive and negative coincidence, which is why I did that. However, it is definitely confusing as the 55 hits shared by the two-tailed tests in the top heatmap are clearly all examples of negative coincidence as they are picked up by all negative coincidence tests in the bottom panel (so we wouldn't expect them to intersect with the other categories in the top panel anyway).

Hopefully that makes sense. Please let me know if I can clarify anything else! I would be happy to share any of the files I used for this analysis if that's helpful.

**Comment by fwhelan** [comment]
Thanks, Gavin! I've managed to caffeinate and wrap my head around this. I've done a similar set of tests with a small test set and have similar results to what you've found:
![gavin-coinfinder](https://user-images.githubusercontent.com/3144468/140503155-9ce4ac6c-e9ad-43fd-8ba6-ccfee43f6bb9.png)

The strains in this pangenome are really similar to each other which I suspect is why my dissociate-greater isn't as large as my associate-less in comparison to your tests.

I've spent the morning arguing myself into and out of whether associate-less is more/less biologically relevant than dissociate-greater. And, I think, the answer lies in the gene pairs that dissociate-greater says are significant that associate-less does not. In my small test, there were a number of different gene-gene pairs, but only 1 additional node/gene in dissociate-greater, so I focused on it (group_2949). It formed 2 edges with the genes on either side of it in this presence/absence heatmap:
![gavin_heatmap](https://user-images.githubusercontent.com/3144468/140506114-868b1647-849b-4b6f-a14f-99a21e672602.png)
And, really, those relationships don't look like dissociation relationships to me. ...But on the other hand, mathematically dissociate-greater makes sense to me.

What do you think?

**Comment by gavinmdouglas** [comment]
Hey Fiona,

Thanks for sharing all of this!

Hmm yes those don't look like really clear dissociation relationships to me either, but I'm certainly no expert.

I think the key thing that I'm confused about is why the number of significant hits for the dissociation and association tests are so different - do you think maybe dissociation tests have slightly higher power for some reason? To me the association and dissociation tests are really similar mathematically, but clearly they produce different results based on real data.

I made a quick example to show how I was expecting the tests to perform. I did this by simulating random gene pairs across 50 genomes. The numbers of genomes and which genomes each gene occurs across was sampled totally randomly. I then ran all six binomial tests, which I think match with what coinfinder is doing.

Anyway, you can see that the associate_less and the dissociate_greater (as well as the associate_greater and the associate_less) produce really similar p-value distributions (but not identical!). Basically I was assuming that the resulting significant hits with real data should also be similar based on this property, but apparently not!

<img width="1551" alt="Screen Shot 2021-11-05 at 10 09 18 AM" src="https://user-images.githubusercontent.com/12489683/140524620-8bf9a58c-2643-48f7-ab4b-27e14cfaadc6.png">

This is the r code that I used to simulate the data and make this plot:

```
### Sample replicates of two genes with random counts from 1:50, representing the
### number of genomes they are found across. Then randomly sample the number of genomes
### that encode both. Perform all 6 types of association/dissociation binomial tests.

rm(list = ls(all.names = TRUE))

num_rep <- 10000

coinfinder_testing <- data.frame(matrix(NA, nrow = num_rep, ncol = 18))
colnames(coinfinder_testing) <- c("gene1_occurences", "gene2_occurences",
                                  "exp_intersects", "obs_intersects",
                                  "associate_less_p", "associate_less_estimate",
                                  "associate_greater_p", "associate_greater_estimate",
                                  "associate_twotailed_p", "associate_twotailed_estimate",
                                  
                                  "exp_nonintersects", "obs_nonintersects",
                                  "dissociate_less_p", "dissociate_less_estimate",
                                  "dissociate_greater_p", "dissociate_greater_estimate",
                                  "dissociate_twotailed_p", "dissociate_twotailed_estimate")

for (rep_i in 1:num_rep) {
 
  gene1_occurences <- sample(1:50, size = 1) 
  gene2_occurences <- sample(1:50, size = 1)
  
  gene1_genomes <- sample(1:50, size = gene1_occurences)
  gene2_genomes <- sample(1:50, size = gene2_occurences)
  
  gene1_p <- gene1_occurences / 50
  gene2_p <- gene2_occurences / 50
  
  exp_intersects <- gene1_p * gene2_p * 50
  obs_intersects <- length(which(gene1_genomes %in% gene2_genomes))
  
  exp_nonintersects <- (gene1_p * (1 - gene2_p) + gene2_p * (1 - gene1_p)) * 50
  obs_nonintersects <- length(which(! gene1_genomes %in% gene2_genomes)) + length(which(! gene2_genomes %in% gene1_genomes))
  
  associate_less_out <- binom.test(x = obs_intersects, n = 50, p = exp_intersects / 50, alternative = "less")
  associate_greater_out <- binom.test(x = obs_intersects, n = 50, p = exp_intersects / 50, alternative = "greater")
  associate_twotailed_out <- binom.test(x = obs_intersects, n = 50, p = exp_intersects / 50, alternative = "two.sided")
  
  dissociate_less_out <- binom.test(x = obs_nonintersects, n = 50, p = exp_nonintersects / 50, alternative = "less")
  dissociate_greater_out <- binom.test(x = obs_nonintersects, n = 50, p = exp_nonintersects / 50, alternative = "greater")
  dissociate_twotailed_out <- binom.test(x = obs_nonintersects, n = 50, p = exp_nonintersects / 50, alternative = "two.sided")
  
  coinfinder_testing[rep_i, "gene1_occurences"] <- gene1_occurences
  coinfinder_testing[rep_i, "gene2_occurences"] <- gene2_occurences
  
  coinfinder_testing[rep_i, "exp_intersects"] <- exp_intersects
  coinfinder_testing[rep_i, "obs_intersects"] <- obs_intersects
  
  coinfinder_testing[rep_i, "associate_less_p"] <- associate_less_out$p.value
  coinfinder_testing[rep_i, "associate_less_estimate"] <- associate_less_out$estimate
  
  coinfinder_testing[rep_i, "associate_greater_p"] <- associate_greater_out$p.value
  coinfinder_testing[rep_i, "associate_greater_estimate"] <- associate_greater_out$estimate
  
  coinfinder_testing[rep_i, "associate_twotailed_p"] <- associate_twotailed_out$p.value
  coinfinder_testing[rep_i, "associate_twotailed_estimate"] <- associate_twotailed_out$estimate
  
  coinfinder_testing[rep_i, "exp_nonintersects"] <- exp_nonintersects
  coinfinder_testing[rep_i, "obs_nonintersects"] <- obs_nonintersects

  coinfinder_testing[rep_i, "dissociate_less_p"] <- dissociate_less_out$p.value
  coinfinder_testing[rep_i, "dissociate_less_estimate"] <- dissociate_less_out$estimate
  
  coinfinder_testing[rep_i, "dissociate_greater_p"] <- dissociate_greater_out$p.value
  coinfinder_testing[rep_i, "dissociate_greater_estimate"] <- dissociate_greater_out$estimate
  
  coinfinder_testing[rep_i, "dissociate_twotailed_p"] <- dissociate_twotailed_out$p.value
  coinfinder_testing[rep_i, "dissociate_twotailed_estimate"] <- dissociate_twotailed_out$estimate
  
  
}

coinfinder_testing_p_values <- coinfinder_testing[, grep("_p$", colnames(coinfinder_testing))]
pairs(coinfinder_testing_p_values)

```

**Comment by fwhelan** [comment]
I love how thorough you work!!

With every message I'm becoming increasingly worried that there is a bug somewhere... (the code base is a bit of a mess).

**Comment by fwhelan** [comment]
But I think this checks out:
```
$ head -n 1 dissociate_greater_pairs.tsv 
Source  Target  p       successes       observations    rate    expected        total source    total target    fraction source fraction target
$ grep "group_2575\s*group_997" dissociate_greater_pairs.tsv 
group_2575      group_997       1.75624e-19     173     199     0.574657        114     140     63      0.703518        0.316583
$ head -n 1 associate_less_pairs.tsv 
Source  Target  p       successes (OA(ij))      observations    expected (EA(ij))       total source    total target    fraction source fraction target
$ grep "group_2575\s*group_997" associate_less_pairs.tsv 
group_2575      group_997       2.25882e-08     15      199     44      140     63      0.703518        0.316583
```
Doin the math by hand, I don't see any errors in the calculations of the observed and expected rates. Then, the code takes successes, rate, number of genomes, and the test type (two-tailed, greater, less) and calculates the p-value via a binomial test. But even in this one off example, the dissociate-greater p-value is much smaller than the associate-less for the same gene pair.

I'm not very strong statistically; I'm not sure how the dissociate-greater could be more powered than the associate-less. Let me do some reading...

**Comment by gavinmdouglas** [comment]
Ah ok interesting to see! It does seem likely that there is more power for that test for some reason. I'm not sure why that would be either, beyond the fact that the expected and observed absolute values of nonintersecting counts are much larger usually than the numbers for the intersecting counts. I wouldn't have thought that would matter before seeing the results of these analyses though!


Just for completion while I still have the simulation data open - here's some more supporting evidence below.

On the basic simulations I ran, the P-values of all random gene pairs that are significant based on _either_ dissociate_greater or associate_less are clearly much lower on average for the dissociate_greater test.

<img width="586" alt="Screen Shot 2021-11-05 at 2 22 59 PM" src="https://user-images.githubusercontent.com/12489683/140560239-f1041bc2-5822-4762-a487-2d1d58380a39.png">


And the log ratio of all p-values for those two tests looks like this, which shows that the p-values are lower overall for the dissociate_greater tests.
<img width="926" alt="Screen Shot 2021-11-05 at 2 19 32 PM" src="https://user-images.githubusercontent.com/12489683/140560327-84bc458a-897d-41b8-9bbf-78f3ebf50810.png">

**Comment by fwhelan** [comment]
This is so cool (slash scary).

Ok, so just to be sure I understand: we're seeing the same phenomenon with coinfinder and with your independent calculations in R, correct? i.e., this isn't a bug but a real phenomenon.

**Comment by gavinmdouglas** [comment]
Haha it is nice when independent analyses line up! Yes it looks like the same phenomenon is coming up these R calculations too!

**Comment by fwhelan** [comment]
I'm fascinated! (And relieved that it isn't just an artifact of some poor coding.) Would you be interested in diving into this a bit more with me and trying to sort it out? I completely understand if that's outside of your interests!!

**Comment by gavinmdouglas** [comment]
Sure I would be happy to! I'll ask around and see if I come across anything online.

**Comment by gavinmdouglas** [comment]
I asked my labmates about this and the consensus seems to be that this is a similar problem to calculating linkage disequilibrium (and linkage equilibrium) and that much like in that case, that they are not simply complements of each other like I was thinking. This is because, as the equation for dissociation describes in the coinfinder paper, that there are two ways of seeing one gene and not the other. In contrast, there is only one way to see a 'success' in terms of association. So that means that it makes sense that the distributions (and the resulting outputs) are different. I think that also explains why the dissociation test has more power to detect dissociative relationships.

**Comment by fwhelan** [comment]
Hmmm that's quite interesting, reassuring as well.

I guess what's bothering me is the question of which is more biologically relevant- I don't like the idea that we can describe dissociation relationships (I would argue) in one of two ways- one must be more "correct" than the other, surely. I also don't like the dissociate-greater relationship that I screenshoted above getting through the analysis. I had also seen some less-than-ideal relationships come out of a large (>8000) genome dataset but hadn't had a chance to revisit it; I'm running associate-less on a few datasets now to see how it compares.

Longer term, I suppose I'm wondering: if we think that associate-less might be more biologically relevant (and can demonstrate that) that we should update the coinfinder defaults to use associate-less and write a short application note to document the change (and reason for it) to the community.

**Comment by gavinmdouglas** [comment]
I'm definitely still confused about this, but I think essentially that the associate_less test is a lowered power test for dissociation compared to the dissociate_greater as the associate_less is only based on one variable (the proportion of genomes where the genes co-occur) while the dissociate_greater test considers more information.

It would be interesting to know whether the associate-less results were always a subset of the dissociate-greater results in your analysis. However, I totally agree that if you find that the associate-less results just seem to make more sense based on manual validation then perhaps that should be the recommended approach! I'll ask my labmates to see if they want to chime in one this too.

**Comment by fwhelan** [comment]
Cool, I'll do a bit of testing (hopefully over the next few days, famous last words) and put together some rudimentary figures to see what you think.

Or course re your labmates; the more the merrier!
