### ISSUE TITLE
Feature request: Looking at Specific Genes

### ISSUE THREAD

**Issue by spencer411** [fwhelan/coinfinder#47]
First off, great tool! 

I am currently working on a project where we are examining coincident relationships between AMR genes and other accessory genes. This program has been great, but for our specific case the number of overall coincident genes is so huge it is difficult to sift through, especially given that many coincident genes with our AMR genes are also coincident genes with other genes.

Have you considered making a feature where users can flag certain genes of interest and coinfinder will return only coincident genes results for those specific genes/gene clusters? This would make for a far more publishable heatmap and network diagram in our case. I think we can work what we have now, but just thought I'd bring it up as I have several other projects in the pipeline where I would like to use this program in a similar capacity.

Thanks again!

**Comment by fwhelan** [comment]
Hi spencer411,

Actually, this feature already exists! If I understand correctly I think its the `-q` or `--query` flag that you're looking for which takes the gene name as input (e.g., `coinfinder -i gene_p_a.csv -I -p tree.newick -q lacZ`). Currently, coinfinder can only take a single gene in this way, but it wouldn't be too difficult to update this to take a list of genes (e.g., AMR genes of interest)- would that be helpful?

**Comment by spencer411** [comment]
Oh great! I really need to start looking at these github pages closer! I definitely think the list option would be nice, as many of our AMR genes are coincident with each other, that way a nice network diagram which shows the relationship between all of the AMR genes and their co-circulating friends would be possible. Thanks so much!

**Comment by fwhelan** [comment]
Great! Ok, give me a few days to see if I can add in that functionality! When I've got that done, I'll release a new version, and update the github page to make this functionality more obvious.

**Comment by fwhelan** [comment]
Hi spencer411. I've just committed an update to coinfinder that will take a file name (instead of an individual gene ID) with the `-q` flag. The file is then expected to have one gene per line that you wish to subset your results to. I've given it a little test but please let me know if you run into any issues with it.

Do you use coinfinder via bioconda? I'm having a small issue getting the newest version up onto bioconda which I can hopefully get fixed tomorrow.

**Comment by spencer411** [comment]
Amazing thank you! Yes I am using the conda version, but I can wait. I really appreciate it, we have a project we will use it for ASAP!

**Comment by fwhelan** [comment]
It took a long time, but the conda version is finally updated! Please let me know if you have any issues with this new functionality (feel free to reopen this issue as needed!).
