### ISSUE TITLE
CMake Error at CMakeLists.txt:2 (project)

### ISSUE THREAD

**Issue by RJBeng** [fwhelan/coinfinder#5]
Hello, 

I am trying to install coinfinder on Linux and having problem running the first step. After running 

```cmake -DCMAKE_BUILD_TYPE=Release .```

I am getting the following error

```-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    /usr/bin/cc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/c++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

When I run ```which cc``` and ``` which c++``` I get the following paths respectively

```/usr/local/bin/cc``` and ```/usr/local/bin/c++```

I am not sure how to edit the CMakeLists.txt so it searches the right path.

**Comment by fwhelan** [comment]
Hi RJBeng,

The error is saying that `cmake` doesn't know where to find your two compilers. You have the option of setting the environment variables or to alter the `CMakeLists.txt` file to manually set the variables in question (`CMAKE_C_COMPILER`, `CMAKE_CXX_COMPILER`) so that `cmake` can find them. I've included an example of each way of doing this below for you to try out.

Setting the environment variable:
In your terminal/shell: `export CC=/usr/local/bin/cc`. This will assign the variable `CC` the path to your compiler for the length of time that you have your terminal open (to make this more permanent, you could add this line to your `.bashrc`).

Altering `CMakeLists.txt`:
In something like GEdit, nano, or vim: you could add the line `set(CMAKE_C_COMPILER "/usr/local/bin/cc")` to the file, somewhere near the beginning. Save, and retry to build.

Let me know how you get on with these!

**Comment by RJBeng** [comment]
Hi @fwhelan,

Thanks for getting back to me so quickly. I have just tried both methods, setting the environment variable and altering the ```CMakeList.txt``` but I am still getting the same error :(

I have attached a copy of the edited ```CMakeList.txt``` 

[CMakeLists.txt](https://github.com/fwhelan/coinfinder/files/3798748/CMakeLists.txt)

Thanks

**Comment by fwhelan** [comment]
If you type `echo $CC` in your shell, does it return `/usr/local/bin/cc`?

**Comment by RJBeng** [comment]
Yes it does.

I have also tired building this on my mac, but now im getting a different set of errors when running the first step.

```CMake Warning at /usr/local/lib/cmake/boost_filesystem-1.71.0/libboost_filesystem-variant-static.cmake:59 (message):
  Target Boost::filesystem already has an imported location
  '/usr/local/lib/libboost_filesystem-mt.a', which will be overwritten with
  '/usr/local/lib/libboost_filesystem.a'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_filesystem-1.71.0/boost_filesystem-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindBoost.cmake:261 (find_package)
  CMakeLists.txt:20 (find_package)


CMake Warning at /usr/local/lib/cmake/boost_system-1.71.0/libboost_system-variant-static.cmake:59 (message):
  Target Boost::system already has an imported location
  '/usr/local/lib/libboost_system-mt.a', which will be overwritten with
  '/usr/local/lib/libboost_system.a'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_system-1.71.0/boost_system-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindBoost.cmake:261 (find_package)
  CMakeLists.txt:20 (find_package)


-- Boost  found.
-- Found Boost components:
   filesystem;system
CMake Error at CMakeLists.txt:60 (include_directories):
  include_directories given empty-string as include directory.


-- Configuring incomplete, errors occurred!
See also "/Users/Applications/coinfinder/CMakeFiles/CMakeOutput.log".
````
[CMakeOutput.log](https://github.com/fwhelan/coinfinder/files/3798785/CMakeOutput.log)

**Comment by fwhelan** [comment]
Hi RJBeng,

Have you made any progress here? Do you want to try to troubleshoot this on your mac or linux envrionment?

**Comment by RJBeng** [comment]
Hi @fwhelan, I am still bumping into the same issue as before :( it would be good to troubleshoot this on the linux environment.

**Comment by fwhelan** [comment]
Could you try your edited CMakeLists.txt on a fresh pull of the repo? Or alternatively, could you remove the CMakeCache.txt that was generated from your initial runs of `cmake`? I'm wondering if the changes you've made haven't been updated in the CMakeCache.txt and so aren't being seen by `cmake`.

**Comment by RJBeng** [comment]
Hi @fwhelan, I have pulled a fresh repo and edited the CMakeLists.txt and now its finally working! Thank you so much for your help!

**Comment by joana-morais** [comment]
I'm having the same issue and fresh pulling of the repo didn't work. 

I get this error: 

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

**Comment by fwhelan** [comment]
Hi joana-morais. Is installing via `conda` or `mamba` an option for you? I would suggest those if they are as they'll be a lot more straight forward. Otherwise, can you follow the steps above (e.g., try setting the enviornment variables for your compileter in the CMakeList file) and let me know how you get on?
