### ISSUE TITLE
Using a tree generated with RAxML hangs at tree loading step

### ISSUE THREAD

**Issue by fwhelan** [fwhelan/coinfinder#50]
Would be ideal if RAxML outputs could be used; if not, test the format of the tree at start up and output error message if it's not in a format that the tree loading step can handle before running code.

**Comment by edsonmachado** [comment]
Hi @fwhelan,

I'm trying to run an analysis based on a phylogeny generated with RAxML and having the following error (R code step):

**command line:** coinfinder --input ../../PanGenome/Roary/gene_presence_absence.csv --inputroary --phylogeny ../../Phylogeny/MKC.FINAL.raxml.support --associate --level 0.05 --bonferroni --greater --num_cores 80 --verbose --output ASSOCIATE

Reading arguments...
> CORRECTION ······· = BONFERRONI
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = YES
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = ../../PanGenome/Roary/gene_presence_absence.csv
> GENE_NAME ······· = Genes
> GENOME_NAME ········ = Genomes

...


**ERROR MESSAGE FROM R:
Error in comparative.data(phy = treeRt, data = annot, names.col = Id,  :
  Labels duplicated between tips and nodes in phylogeny**

Does this error related to this Issue? Any tip about the solution for my case?

Thanks!

**Comment by fwhelan** [comment]
I think it could, yes. I would suggest converting your Raxml output to newick before input into coinfinder.
