### ISSUE TITLE
Feature request: Heatmap output as gridded data (csv/tsv)

### ISSUE THREAD

**Issue by amymariecampbell** [fwhelan/coinfinder#56]
It would be really helpful if, as well as the great visual output of the heatmap, this information could be provided in some kind of gridded data format- with rows representing samples and the columns representing the gene groups. The different clusters would perhaps need to be assigned numbers rather than colours which would be inputted into the cells where the colour blocks are in the tree.  This would be really great for downstream analysis, particularly as I'm trying to work out any spatiotemporal links between the coincident genes. Hope that makes sense!

**Comment by fwhelan** [comment]
That makes complete sense and is a really great idea! This is already coded in the R code that generates the heatmap, so it was a pretty easy addition. I've just pushed it now and will make a new version of coinfinder now which will push to conda automatically.

Let me know if you run into any issues with it! And thank you for your patience.

**Comment by amymariecampbell** [comment]
Great thanks Fiona! Do we need to specify as an option or is it an automatic output?

**Comment by fwhelan** [comment]
Hi amymariecampbell. It's automatic, but note that you'll need the most recent version [v1.2.1](https://github.com/fwhelan/coinfinder/releases/tag/1.2.1).

**Comment by amymariecampbell** [comment]
Is Version 1.2.1 available on Conda? I just tried to update but my version is still 1.1
Thanks again!
________________________________

**Comment by fwhelan** [comment]
Hi amymariecampbell. Conda should at least be giving you 1.2.0 which was merged into bioconda in May 2022?

As for 1.2.1, I had labelled it as a pre-release so I don't think was automatically picked up by bioconda's bot to automerge it into bioconda. I've changed this now, so it should be updated in bioconda within 48hours; please let me know if it's not, though, and I'll follow up and merge it manually :).

Thanks!

**Comment by fwhelan** [comment]
Hi amymariecampbell. Sorry it took so long; bioconda's version of coinfinder should now be v1.2.1. Let me know if you still have any issues accessing it!

Thanks for your patience!
