### ISSUE TITLE
install dlib

### ISSUE THREAD

**Issue by Mirzasalman11** [fwhelan/coinfinder#59]
Collecting dlib
  Using cached dlib-19.24.0.tar.gz (3.2 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using legacy 'setup.py install' for dlib, since package 'wheel' is not installed.
Installing collected packages: dlib
  Running setup.py install for dlib: started
  Running setup.py install for dlib: finished with status 'error'
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data[ in a text editor](command:workbench.action.openLargeOutput?f41b5bab-1dcc-491c-89dc-d45f867a951c)
  error: subprocess-exited-with-error
  
  × Running setup.py install for dlib did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      running install
      running build
      running build_py
      package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
      running build_ext
      Building extension for Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
      Invoking CMake setup: 'cmake C:\Users\salma\AppData\Local\Temp\pip-install-agbu0ohp\dlib_fad1572b41f2473abb5a9035d4da5b3a\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\salma\AppData\Local\Temp\pip-install-agbu0ohp\dlib_fad1572b41f2473abb5a9035d4da5b3a\build\lib.win-amd64-3.10 -DPYTHON_EXECUTABLE=C:\Users\salma\AppData\Local\Programs\Python\Python310\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\salma\AppData\Local\Temp\pip-install-agbu0ohp\dlib_fad1572b41f2473abb5a9035d4da5b3a\build\lib.win-amd64-3.10 -A x64'

**Comment by fwhelan** [comment]
Hi Mirzasalman11- sorry, could you give me some more context here? What command are you running that generates this error?

**Comment by fwhelan** [comment]
Closed due to inactivity.
