### ISSUE TITLE
Error: cannot open file './coinfind-code/check_zeroes.R'

### ISSUE THREAD

**Issue by BurinkiWU** [fwhelan/coinfinder#60]
Hello, 
The following problem was attached below,
/home/disk3-8T/wzq/tools/coinfinder/coinfinder -i gene_presence_absence.csv -p accessory_binary_genes.fa.newick -o coinfinder_output --associate
Reading arguments...
> CORRECTION ······· = BONFERRONI
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = NO
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = gene_presence_absence.csv
> GENE_NAME ······· = Genes
> GENOME_NAME ········ = Genomes
ERROR MESSAGE FROM R:
error: cannot open file './coinfind-code/check_zeroes.R': No such file or directory

What is going on? 

Please help!

**Comment by fwhelan** [comment]
Hi BurinkiWU, apologies for not getting back to you sooner on this issue. How did you install coinfinder? If you install via conda you shouldn't run into this issue...

**Comment by fwhelan** [comment]
Closed due to inactivity.
