### ISSUE TITLE
Zero length branch fix

### ISSUE THREAD

**Issue by bananabenana** [fwhelan/coinfinder#61]
Hi,

First off, just wanted to say this tool and the coinfinder paper, and the subsequent E. coli analysis paper are amazing. Incredible contributions.

Just wanted to leave a resolved solution for anyone else who gets an issue with highly-related species with zero branch lengths and gets the following error message:
```
The R function caper::phylo.d, which coinfinder uses to define lineage dependence, cannot handle zero length branches.
```
Instead of collapsing branches, you can fix this by adding a very small value to branch lengths in R.  The following code should be executed in R:

```
# Load libraries
library(ape)

# Load data
tree<- read.tree("tree.nwk")

# Add small value to branch length
tree[["edge.length"]] <- tree[["edge.length"]]+1e-6 # could go even smaller, just demonstrating

write.tree(tree, file='tree_1e-06.nwk')
```

This `tree_1e-06.nwk` can then be successfully used with the `-p` flag.
Well, this worked for me.

**Comment by fwhelan** [comment]
Thanks so much for posting this solution, @bananabenana ! This is very similar to what I do when faced with this issue as well, but its very appreciated to have it outlined in detail here :)
