### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by MHassanSaeed** [fwhelan/coinfinder#64]
Hi,

I tried running coinfinder using my own and example files (core-gps_fasttree.newick & gene_presence_absence.csv) but I'm getting following error:
``
coinfinder -i /home/ubuntu/gene_presence_absence.csv  -p core-gps_fasttree.newick -o ./genomes/coin -a a -m -c -g -v --all --output coin 
Reading arguments...
> CORRECTION ······· = FRACTION (special)
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = YES
> OUTPUT_ALL ······· = YES
Aborted (core dumped)
``
Best,
Hassan

**Comment by fwhelan** [comment]
Hi Hassan,
Could you give me a few more details: version of coinfinder, how you installed it etc?

Thanks.

**Comment by MHassanSaeed** [comment]
Hi,

I installed it with mamba:
firstly remove and add channels for conda
then brew install 
finally mamba install -c defaults -c bioconda -c conda-forge coinfinder

While I was checking its version, it display the following arguments:
> CORRECTION ······· = NONE
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = YES
> VERBOSE ·········· = YES
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05

Thanks

**Comment by qducarmon** [comment]
I have exactly the same issue unfortunately after following the installation instructions in issue #36 from drelo, wondering if there is solution for this already?. This is my exact output

```
Reading arguments...
> CORRECTION ······· = NONE
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = YES
> VERBOSE ·········· = YES
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
terminate called after throwing an instance of 'std::logic_error'
  what():  Alpha file is missing.
Aborted (core dumped)
```

**Comment by fwhelan** [comment]
Hi both,

Can you confirm the date of the release build (by just typing `coinfinder` on the commandline). I'm trying to reproduce your error now; it would be helpful to know exactly how you called coinfinder too.

**Comment by MHassanSaeed** [comment]
Hi,

I checked and found something went wrong after other installations/updates - I tried reinstalling but it's having solving environment problem.

Unfortunately, I couldn't share the release date.

**Comment by fwhelan** [comment]
Ok, no worries; I'll close this issue but feel free to open it if you're still having this issue in the future.
