### ISSUE TITLE
Problem with phytools

### ISSUE THREAD

**Issue by AntoniaHab** [fwhelan/coinfinder#65]
Hi Fiona,

thank you so much for making coinfinder available. It is exactly what I was looking for.

I am having an issue with the phytools package (? I think). When trying to run coinfinder, I get the following error message:

Error: package or namespace load failed for ‘phytools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/anaconda3/envs/coinfinder-env/lib/R/library/Matrix/libs/Matrix.dylib':
  dlopen(/opt/anaconda3/envs/coinfinder-env/lib/R/library/Matrix/libs/Matrix.dylib, 0x0006): Library not loaded: @rpath/R/lib/libRlapack.dylib
  Referenced from: <C143BE3C-014E-3126-9619-424EB6AB3CD2> /opt/anaconda3/envs/coinfinder-env/lib/R/library/Matrix/libs/Matrix.dylib
  Reason: tried: '/opt/anaconda3/envs/coinfinder-env/lib/R/lib/libRlapack.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/coinfinder-env/lib/R/lib/libRlapack.dylib' (no such file), '/opt/anaconda3/envs/coinfinder-env/lib/R/library/Matrix/libs/../../../lib/R/lib/libRlapack.dylib' (no such file), '/opt/anaconda3/envs/coinfinder-env/lib/R/library/Matrix/libs/../../../../R/lib/libRlapack.dylib' (no such file), '/opt/anaconda3/envs/coinfinder-env/lib/R/lib/libRlapack.dylib' (no such 

I get the same error message when just running > library(phytools) in the R terminal.

I tried installing phytools (> install.packages('phytools')), but I get a non-zero exit status notification.

From what I get from the first error message, I assume this is a problem with the Matrix package?
When I try to load this package, I get the same error message as when loading phytools. I also tried to install Matrix with install.packages('Matrix'), but I also get a non-zero exit status notification.

Do you have an idea what I could do to solve this issue?

I just installed coinfinder yesterday and have the 1.1 version (release build @ Feb 22 2023).
I use MacOS Ventura 13.3.1.

Thank you,
Antonia

**Comment by fwhelan** [comment]
Hi Antonia,

How did you install coinfinder?

**Comment by fwhelan** [comment]
Closed due to inactivity.
