### ISSUE TITLE
Write permissions error 'coincident-input-edges.csv'

### ISSUE THREAD

**Issue by dannagifford** [fwhelan/coinfinder#66]
Unsure if feature request or bug report!

Situation: When I run coinfinder from an arbitrary path (e.g. where my roary output lives), coinfinder is trying to write 'coincident-input-edges.csv' where the coinfinder binary lives. I've compiled coinfinder from source in /usr/local/src/coinfinder-master/ in a Linux environment, which is owned by root.

Desired outcome: It would be nice if coinfinder wrote this file in a user-definable spot rather than where the binary happens to be run from.

Workaround: I temporarily changed the ownership of /usr/local/src/coinfinder-master/ to my user, which allowed the output to be generated. However, this is not ideal as (1) this is a multi-user server where (2) multiple users could be in theory trying to run coinfinder at the same time (and overwriting each others' files)

Suggested fix: Change instances of  'coincident-input-edges.csv' to allow writing in the current working directory or a user-defined output path. However, I'm not sure if there are other files that coinfinder also might be trying to write in the same path as the executable, as my workaround will have temporarily fixed all similar problems.

'coincident-input-edges.csv' appears in:
coinfind-code/main.cpp
coinfind-code/format_roary.py

**Comment by dannagifford** [comment]
Following up on this, the workaround might not work fully as I found another error in this run where the coincidence_analysis.tsv file wasn't found (probably not created, possibly due to the same issue?)

Generate gexf formatted network...
grep: /home/myusername/PROJECT/genomes/pangenome_output/coincidence_analysis_components.tsv: No such file or directory
Error: Gexf could not find the alpha name acnA in the components file.
Generate gml formatted network...
grep: /home/myusername/PROJECT/genomes/pangenome_output/coincidence_analysis_components.tsv: No such file or directory
Error: Gml could not find the alpha name acnA in the components file.

**Comment by fwhelan** [comment]
Thanks, Danna- sorry this is causing you issues!

Definitely a bug; when I run a quick test, coincident-input-edges.csv is generated in the working folder as opposed to the coinfinder src folder. I assume given that you mention roary, that you're using the `-i file -I ` options, which means the code should call format_roary.py from your working directory and write coincident-input-edges.csv to the working directory too.

I'm a bit stumped... but to give me the chance to sleep on it, I'll ask: how did you call coinfinder? and (might be unrelated) what's the output of `which coinfinder`?

**Comment by fwhelan** [comment]
Closed due to inactivity; please feel free to re-open if this is still an issue!
