### ISSUE TITLE
Problem with read.newick() causes no heatmap or network to be produced

### ISSUE THREAD

**Issue by dannagifford** [fwhelan/coinfinder#67]
This might be a bug with phytools or RAxML rather than coinfinder, but the error message from coinfinder makes it tricky to figure out what exactly has gone wrong, so I'll raise an issue here.

**Description:** 
I ran coinfinder within its own path (so not related to the other issue I raised about running from /usr/local/src), with gene_presence_absence.csv in the same path.

nohup ./coinfinder -n -x 4 -i  gene_presence_absence.csv -I -p RAxML_bestTree.txt -o coincidence_analysis --associate &> nohup_coinfinder.out &
Input files: [gene_presence_absence.csv](https://github.com/fwhelan/coinfinder/files/11725620/gene_presence_absence.csv)
[RAxML_bestTree.txt](https://github.com/fwhelan/coinfinder/files/11725623/RAxML_bestTree.txt)

```
coinfinder fails to complete, generating the following error message:
Generate gexf formatted network...
grep: coincidence_analysis_components.tsv: No such file or directory
Error: Gexf could not find the alpha name acnA_1 in the components file.
Generate gml formatted network...
grep: coincidence_analysis_components.tsv: No such file or directory
Error: Gml could not find the alpha name acnA_1 in the components file.
All done!
```

This points towards the "coincidence_analysis_components.tsv" file being absent. I tracked to where this file is being generated: network.R. I then ran this script line-by-line on my gene_presence_absence.csv file, setting the opts manually.

What seems to be happening for me is that network.R is getting stuck when reading in my RAxML file with phytools::read.newick(). The same tree reads in fine with ape::read.tree(). If I change the script to use ape::read.tree() instead of phytools::read.newick(), the script completes as intended.

**Workaround**
Replace read.newick(opt$phylogeny) from phytools with read.tree(opt$phylogeny) from ape in network.R. Is there a reason to use one over the other?
Line in code is here: https://github.com/fwhelan/coinfinder/blob/9c20ef0b6fbeaab1fba99806dfeeb70ecf4db22c/coinfind-code/network.R#LL30C1-L31C1

**Comment by fwhelan** [comment]
Hmm, you might have inadvertently solved issue #50 !

I can't remember why I chose one over the other; likely not for much reason. A quick google suggests they should be redundant of each other (e.g. https://rdrr.io/cran/phytools/man/read.newick.html) but then I wonder why one hangs and the other doesn't?
