### ISSUE TITLE
Gexf file is zero bytes

### ISSUE THREAD

**Issue by STChoudhury** [fwhelan/coinfinder#68]
Hi I am running coinfinder and I have the following issue:

Error: unable to open coincident_nodes.tsv
Generate coincidence heatmap...
Generate network...
grep: coincident_components.tsv: No such file or directory
Error: Gexf could not find the alpha name RBKS in the components file. 

My command line is as follows:
 
coinfinder  -i gene_presence_absence_roary_withquotes.csv -I -p RAxML_bestTree.raxml_core_output -a -m

Can you please help me with this?

Thank you,
Sam

**Comment by fwhelan** [comment]
Hi Sam- so sorry to keep you waiting!! What is in your output folder? Are there any files that begin with `coincident_`? If `coincident_nodes.tsv` exists, what does it look like (for e.g., the output of `head coincident_nodes.tsv` on the commandline).

It might be unrelated, but it could be a small formatting difference in your gene_presence_absence file; did you use Panaroo to generate it?

**Comment by fwhelan** [comment]
closed due to inactivity, please feel free to open again if this is still an issue.
