### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by cocathail** [fwhelan/coinfinder#7]
Hi there,

Running coinfinder throws a python error. It seems that it's having trouble with the csv file I'm giving it but it's the csv output from roary without any changes made so not sure why it's not playing nice. See below:

adac_guest@dsbadacd1:/media/adac_guest/Data2/Colman/EC_anno$ coinfinder -i E_coli_presence_absence.csv -p E_coli_cg_aln-PhyML_tree.nwk -o amr_coin --associate
Reading arguments...
> CORRECTION ······· = BONFERRONI
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = NO
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = E_coli_presence_absence.csv
> ALPHA_NAME ······· = Alpha
> BETA_NAME ········ = Beta
Formating input into gene_p_a for input into coinfinder...
ERROR MESSAGE FROM Python:
Traceback (most recent call last):
  File "/home/adac_guest/coinfinder///coinfind-code/create_roary.py", line 57, in <module>
    gen = (line.split("\t")[1]).strip()
IndexError: list index out of range

Colman

**Comment by fwhelan** [comment]
Hi Colman,

If you're data is in Roary's csv format, you'll have to include the `-I` flag to your call (for e.g. `coinfinder -i E_coli_presence_absence.csv -I -p E_coli_cg_aln-PhyML_tree.nwk -o amr_coin --associate`

More information can be found by running `coinfinder -h`.

Let me know if that solves it!

**Comment by cocathail** [comment]
Thanks! Works great
