### ISSUE TITLE
Using coinfinder for very divergent species

### ISSUE THREAD

**Issue by AnnaLew** [fwhelan/coinfinder#74]
Hello,

I have a more general question regarding the use of coinfinder. I am working with very divergent species, therefore panaroo couldn't find any core genome. I used MMseqs2 and managed to find clusters of genes which I then divided into the core, shell, and cloud genomes. I am wondering whether coinfinder is a good choice in my case, or perhaps with such divergent data it might not find anything and I will just waste time and resources running it. If that's the case, can you recommend another tool? I'd be very grateful for any advice!

**Comment by fwhelan** [comment]
Hi AnnaLew, if you have gene groups that you're finding across your pangenome (i.e. shell/cloud genes, depending on definitions) then it's possible for coinfinder to find gene-gene co-occurrences between them. Coinfinder doesn't rely on the need for a core genome as such.
Hope that helps!
